// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM89UQyKVoHYB0U-EhqLdFkSbdkK6plak',
    appId: '1:1026803930557:web:f1d59c04cb4fdfcce56ed4',
    messagingSenderId: '1026803930557',
    projectId: 'nine-workout',
    authDomain: 'nine-workout.firebaseapp.com',
    storageBucket: 'nine-workout.firebasestorage.app',
    measurementId: 'G-GWBST3CLXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjlwdPupc3ADBKZ3hK4rvHrf7mXWkj7IY',
    appId: '1:1026803930557:android:0bb120e82f3420aee56ed4',
    messagingSenderId: '1026803930557',
    projectId: 'nine-workout',
    storageBucket: 'nine-workout.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAHcZbd6Z0P7YxS8PigGrebk_oWyM7O7I',
    appId: '1:1026803930557:ios:1e182f7e9eb9f36ee56ed4',
    messagingSenderId: '1026803930557',
    projectId: 'nine-workout',
    storageBucket: 'nine-workout.firebasestorage.app',
    iosBundleId: 'com.example.nineWorkout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAHcZbd6Z0P7YxS8PigGrebk_oWyM7O7I',
    appId: '1:1026803930557:ios:1e182f7e9eb9f36ee56ed4',
    messagingSenderId: '1026803930557',
    projectId: 'nine-workout',
    storageBucket: 'nine-workout.firebasestorage.app',
    iosBundleId: 'com.example.nineWorkout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM89UQyKVoHYB0U-EhqLdFkSbdkK6plak',
    appId: '1:1026803930557:web:3b1887b8c8917731e56ed4',
    messagingSenderId: '1026803930557',
    projectId: 'nine-workout',
    authDomain: 'nine-workout.firebaseapp.com',
    storageBucket: 'nine-workout.firebasestorage.app',
    measurementId: 'G-905BSX3EJ6',
  );
}
